In [75]:
import numpy as np
import pandas as pd


In [76]:
dffemale = pd.read_csv("/content/female.tsv", names = ["name", "gender"],  sep = "\t")
dfmale = pd.read_csv("/content/male.tsv", names = ["name","gender"], sep = "\t")


In [77]:
dffemale['gender'] = 0
dfmale['gender'] = 1

In [78]:
dffemale.dtypes

name      object
gender     int64
dtype: object

In [79]:
dffemale.info

<bound method DataFrame.info of                       name  gender
0       Nguyễn Thị Mỹ Linh       0
1                    Vi Vi       0
2              Hang Thi Vo       0
3       Yen Phi Nguyen Thi       0
4             Trần Thị Lan       0
...                    ...     ...
999995         Phạm Yến Vi       0
999996         Lương Hường       0
999997           Sarah Sam       0
999998          Luong Hien       0
999999         Dung Nguyễn       0

[1000000 rows x 2 columns]>

In [80]:
dffemale.head()

name  gender
0  Nguyễn Thị Mỹ Linh       0
1               Vi Vi       0
2         Hang Thi Vo       0
3  Yen Phi Nguyen Thi       0
4        Trần Thị Lan       0

In [81]:
dfmale.head()

name  gender
0  Nguyễn Đàm Quốc Huy       1
1         Vu Quang Tin       1
2              Hà Thục       1
3              Phu Pro       1
4           Relsx Nick       1

In [82]:
df = pd.concat([dffemale,dfmale])

In [83]:
df

name  gender
0       Nguyễn Thị Mỹ Linh       0
1                    Vi Vi       0
2              Hang Thi Vo       0
3       Yen Phi Nguyen Thi       0
4             Trần Thị Lan       0
...                    ...     ...
999993         Le Chu Tieu       1
999994          Islam Khan       1
999995      သူရိန္ ကို ကို       1
999996       Ace- Mắu-lạnh       1
999997             Hang Bi       1

[1999998 rows x 2 columns]

In [84]:
dffinal = df.sample(frac = 1)

In [85]:
dffinal.head()

name  gender
668019   Lương Thế Hùng       1
198261  Bùi Thiên Hương       0
377034        Thanh Kim       1
477564        Hồng Thoa       0
80501          Đậu Miên       0

In [86]:
print(df.size)
print(dffinal.size)

3999996
3999996


In [87]:
from sklearn.model_selection import train_test_split 
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction import DictVectorizer

In [88]:
names = dffinal["name"]

In [89]:
names

668019       Lương Thế Hùng
198261      Bùi Thiên Hương
377034            Thanh Kim
477564            Hồng Thoa
80501              Đậu Miên
                ...        
308405              Lê Ngọc
327135       Tran Duc Thanh
565250             Phát Đạt
555882          Trang Pilla
180310    Trần Thị Thu Thúy
Name: name, Length: 1999998, dtype: object

In [90]:
names[0]

0    Nguyễn Đàm Quốc Huy
0     Nguyễn Thị Mỹ Linh
Name: name, dtype: object

In [91]:
cv = CountVectorizer()
X = cv.fit_transform(names.values.astype('U'))

In [92]:
cv.get_feature_names()

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['23',
 'aa',
 'aabas',
 'aabb',
 'aabc',
 'aabdallah',
 'aabdltif',
 'aabed',
 'aabedelli',
 'aabha',
 'aabhay',
 'aabhishek',
 'aabid',
 'aacc',
 'aaccem',
 'aacu',
 'aad',
 'aadan',
 'aadarsh',
 'aadel',
 'aadesak',
 'aadesh',
 'aadhil',
 'aadhvik',
 'aadi',
 'aadii',
 'aadil',
 'aadim',
 'aadish',
 'aadito',
 'aaditya',
 'aae',
 'aafaque',
 'aafiya',
 'aaftab',
 'aag',
 'aage',
 'aagle',
 'aahil',
 'aahka',
 'aahmad',
 'aahmed',
 'aahna',
 'aahıl',
 'aai',
 'aaiza',
 'aaj',
 'aajad',
 'aak',
 'aakal',
 'aakash',
 'aakheb',
 'aakib',
 'aakriti',
 'aal',
 'aalam',
 'aalamtrader',
 'aalborg',
 'aali',
 'aalia',
 'aalif',
 'aalim',
 'aalinarrohman',
 'aalisha',
 'aaliya',
 'aaliyah',
 'aalpha',
 'aam',
 'aaman',
 'aamer',
 'aamhi',
 'aamin',
 'aamir',
 'aamirul',
 'aamis',
 'aamri',
 'aan',
 'aanand',
 'aanas',
 'aandtt',
 'aang',
 'aanh',
 'aanhthu',
 'aanika',
 'aanil',
 'aanjana',
 'aann',
 'aannao',
 'aanne',
 'aannhh',
 'aansari',
 'aap',
 'aaphak',
 'aapon',
 'aapte',
 'aapud',
 

In [109]:
X
y = dffinal.gender

In [110]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.33, random_state=42)

In [120]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train,y_train)

MultinomialNB()

In [119]:
model.score(x_test,y_test)
print("Độ chính xác của mô hình",model.score(X_test, y_test)*100,"%")

Độ chính xác của mô hình 83.49454545454546 %


In [146]:
sample_name = ["Nguyễn Đàm Quốc Huy"]
vector = cv.transform(sample_name).toarray()

In [147]:
vector

array([[0, 0, 0, ..., 0, 0, 0]])

In [148]:
# Nam là 1, Nữ là 0
model.predict(vector)

array([1])

In [145]:
sample_name1 =["Nguyễn Thị Mỹ Linh"]
vector1 = cv.transform(sample_name1).toarray()
model.predict(vector1)

array([0])

In [144]:
sample2 = ["Hang Thi Vo"]
vector2 = cv.transform(sample2).toarray()
model.predict(vector2)

array([0])